######################################################################
# Automatically generated by qmake (2.01a) Sat May 19 15:14:49 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += debugt.h pQLabelLineEdit.h
SOURCES += main.cpp pQLabelLineEdit.cpp
