######################################################################
# Automatically generated by qmake (2.01a) ?? 6? 12 07:13:45 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += ../ 

# Input
HEADERS += MainWindow.h ../pQMenuTabWidget.h
SOURCES += main.cpp ../pQMenuTabWidget.cpp
