######################################################################
# Automatically generated by qmake (2.01a) ?? 7? 12 22:25:35 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += MainWindow.h pQMenuTabWidget.h
SOURCES += main.cpp pQMenuTabWidget.cpp
